#### general settings
name: github
use_tb_logger: true
model: denoising
distortion: [hazy]
gpu_ids: [0]



sde:
  max_sigma: 10
  T: 100
  schedule: cosine # linear, cosine
  eps: 0.005

degradation: # for some synthetic dataset that only have GTs
  # for denoising
  sigma: 25
  noise_type: G # Gaussian noise: G

  # for super-resolution
  scale: 4
  
#### datasets
datasets:
  train:
    name: Train_Dataset
    mode: LQGT #MDLQGT
    dataroot_GT: D:\OneDrive\Desktop\The visual computer\sr-diff\datasets\train\hazy\GT
    dataroot_LQ: D:\OneDrive\Desktop\The visual computer\sr-diff\datasets\train\hazy\LQ

    use_shuffle: true
    n_workers: 4  # per GPU
    batch_size: 4 #48 #32
    patch_size: 256
    use_flip: true
    large-size: true
    use_rot: true
    color: RGB
  val:
    name: Val_Dataset
    mode: LQGT #LQGT
    
    #dataroot: /home/q/公共的/ZQ/dense-hazy/test
    dataroot_GT: D:\OneDrive\Desktop\The visual computer\sr-diff\datasets\val\hazy\GT
    dataroot_LQ: D:\OneDrive\Desktop\The visual computer\sr-diff\datasets\val\hazy\LQ
    #dataroot: D:\ZQ\hazy\raindrop

#### network structures
network_G:
  which_model_G: ConditionalUNet
  setting:
    in_nc: 3
    out_nc: 3
    nf: 64
    ch_mult: [1, 2, 4, 8]
    context_dim: 768
    use_degra_context: false
    use_image_context: true

#### path
path:

  pretrain_model_G: ~
  resume_state: ~
  daclip: ~
  strict_load: true

#### training settings: learning rate scheme, loss
train:
  optimizer: AdamW # Adam, AdamW, Lion
  lr_G: !!float 2e-4
  lr_scheme: TrueCosineAnnealingLR # MultiStepLR
  beta1: 0.9
  beta2: 0.99
  niter: 1500000
  warmup_iter: -1  # no warm up
  lr_steps: [200000, 400000, 700000]
  lr_gamma: 0.5
  eta_min: !!float 3e-6
 
  # criterion
  is_weighted: False
  loss_type: l1
  weight: 1.0

  manual_seed: 0
  val_freq: !!float 1e1

#### logger
logger:
  print_freq: 200 #!!float 2e2
  save_checkpoint_freq: !!float 5e3
