name: universal-ir
suffix: ~  # add suffix to saved images
model: denoising
distortion: [rain] # uncompleted means inpainting
gpu_ids: [1]

sde:
  max_sigma: 50
  T: 100
  schedule: cosine # linear, cosine
  eps: 0.005
  sampling_mode: posterior # sde or posterior
  
degradation:
  # for denoising
  sigma: 25
  noise_type: G # Gaussian noise: G

  # for super-resolution
  scale: 4

datasets:
  test1:
   name: Test
   mode: LQGT
   dataroot_GT: /home/q/公共的/ZQ/dense-hazy/test/rain/GT
   dataroot_LQ: /home/q/公共的/ZQ/dense-hazy/test/rain/LQ
  
#### network structures
network_G:
  which_model_G: ConditionalUNet
  setting:
    in_nc: 3
    out_nc: 3
    nf: 64
    ch_mult: [1, 2, 4, 8]
    context_dim: 768
    use_degra_context: false
    use_image_context: true

#### path
path:
  pretrain_model_G: /home/q/公共的/ZQ/daclip-0/daclip-uir-main/daclip-uir-main/experiments/SRdiff-sde/rain/models/625000_G.pth
  #RSM: dense-hazy/train/rain/best_model.pth
